name: Code Quality checks
on:
  pull_request:
    branches: 
      - dev
      - staging
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Format Code
        run: pnpm run format
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}